name: pokemon_explorer
description: "A Pokemon Explorer App."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  # Router 
  go_router: ^14.8.1

  # Icon Launcher
  icons_launcher: ^3.0.1

  # Local Storage
  shared_preferences: ^2.5.2

  # Network
  dio: ^5.8.0+1

  # State Management
  flutter_riverpod: ^2.6.1

  # Code Generation
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  # UI
  infinite_scroll_pagination: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Lint
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

  # Code Generation
  build_runner: ^2.4.15
  freezed: ^3.0.0-0.0.dev
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
